# Test this without rebuilding the docker image $> docker-compose up
# Test this with rebuilding the docker image $> docker-compose up --build

version: '3.7'

services:
  service1:
    build:
      context: .
      dockerfile: Dockerfile-project3
    image: project3:rishabk
    hostname: supernode2
    container_name: supernode2
    working_dir: /csci652/project3
    networks:
      csci652network:
        ipv4_address: 172.28.0.2
    ports:
      - 9091
      - 6969
    command:
      - /bin/bash
      - -c
      - |
        tail -F anything



  service2:
    build:
      context: .
      dockerfile: Dockerfile-project3
    image: project3:rishabk
    hostname: supernode4
    container_name: supernode4
    working_dir: /csci652/project3
    networks:
      csci652network:
        ipv4_address: 172.28.0.3
    ports:
      - 9091
      - 6969
    command:
      - /bin/bash
      - -c
      - |
        tail -F anything


  service3:
    depends_on:
      - service1
      - service2
    build:
      context: .
      dockerfile: Dockerfile-project3
    image: project3:rishabk
    hostname: peer1
    container_name: peer1
    working_dir: /csci652/project3
    networks:
      csci652network:
        ipv4_address: 172.28.0.4
    ports:
      - 6969
      - 9091
    command:
      - /bin/bash
      - -c
      - |
        tail -F anything

  service4:
    depends_on:
      - service1
      - service2
    build:
      context: .
      dockerfile: Dockerfile-project3
    image: project3:rishabk
    hostname: peer2
    container_name: peer2
    working_dir: /csci652/project3
    networks:
      csci652network:
        ipv4_address: 172.28.0.5
    ports:
      - 6969
      - 9091
    command:
      - /bin/bash
      - -c
      - |
        tail -F anything

  service5:
    depends_on:
      - service1
      - service2
    build:
      context: .
      dockerfile: Dockerfile-project3
    image: project3:rishabk
    hostname: peer3
    container_name: peer3
    working_dir: /csci652/project3
    networks:
      csci652network:
        ipv4_address: 172.28.0.6
    ports:
      - 6969
      - 9091
    command:
      - /bin/bash
      - -c
      - |
        tail -F anything

  service6:
    build:
      context: .
      dockerfile: Dockerfile-project3
    image: project3:rishabk
    hostname: client1
    container_name: client1
    working_dir: /csci652/project3
    networks:
      csci652network:
        ipv4_address: 172.28.0.7
    ports:
      - 6969
      - 9091
    command:
      - /bin/bash
      - -c
      - |
        tail -F anything

  service7:
    build:
      context: .
      dockerfile: Dockerfile-project3
    image: project3:rishabk
    hostname: client2
    container_name: client2
    working_dir: /csci652/project3
    networks:
      csci652network:
        ipv4_address: 172.28.0.8
    ports:
      - 6969
      - 9091
    command:
      - /bin/bash
      - -c
      - |
        tail -F anything


networks:
  csci652network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16